# Generated by Django 4.1.7 on 2023-03-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('image', models.ImageField(default='media/b9ddc38e5835fac634678392530003dc.png', upload_to='media/%y')),
            ],
        ),
    ]
